import { z } from "zod";
const nullableDate=z.union([z.string().datetime(),z.null()]).optional();
export const tournamentInputSchema=z.object({
 title:z.string().trim().min(3).max(200),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(180),
 subtitle:z.string().trim().max(255).optional(),description:z.string().trim().max(10000).optional(),gameId:z.number().int().positive(),templateId:z.number().int().positive().nullable().optional(),venueId:z.number().int().positive().nullable().optional(),
 format:z.string().trim().min(2).max(60),participantType:z.enum(["INDIVIDUAL","TEAM"]),teamSize:z.number().int().min(1).max(20),capacity:z.number().int().min(2).max(5000),minParticipants:z.number().int().min(2).max(5000).default(2),price:z.number().int().min(0),
 status:z.enum(["DRAFT","PUBLISHED","REGISTRATION_OPEN","REGISTRATION_CLOSED","DRAW_READY","RUNNING","COMPLETED","POSTPONED","CANCELLED"]),registrationStartsAt:nullableDate,registrationEndsAt:nullableDate,startsAt:z.string().datetime(),endsAt:nullableDate,
 reservationExpiresMin:z.number().int().min(5).max(1440),lateToleranceMin:z.number().int().min(0).max(180),waitlistMode:z.enum(["disabled","offer","manual","automatic"]),allowMultiSlot:z.boolean(),hasThirdPlace:z.boolean(),drawMode:z.enum(["random","seeded","custom"]),
 rules:z.array(z.string().trim().min(1).max(500)).max(100),gameSettings:z.record(z.string(),z.unknown()).default({}),scoringSettings:z.record(z.string(),z.unknown()).default({}),notificationSettings:z.record(z.string(),z.unknown()).default({}),cancellationSettings:z.record(z.string(),z.unknown()).default({}),prizeSettings:z.record(z.string(),z.unknown()).default({}),coverImageUrl:z.string().trim().max(500).nullable().optional(),isFeatured:z.boolean().default(false)
}).superRefine((v,ctx)=>{if(v.participantType==="INDIVIDUAL"&&v.teamSize!==1)ctx.addIssue({code:"custom",path:["teamSize"],message:"اندازه تیم در مسابقه انفرادی باید ۱ باشد."});if(v.minParticipants>v.capacity)ctx.addIssue({code:"custom",path:["minParticipants"],message:"حداقل شرکت‌کننده نمی‌تواند بیشتر از ظرفیت باشد."});const start=new Date(v.startsAt).getTime();const rs=v.registrationStartsAt?new Date(v.registrationStartsAt).getTime():null;const re=v.registrationEndsAt?new Date(v.registrationEndsAt).getTime():null;const end=v.endsAt?new Date(v.endsAt).getTime():null;if(rs&&re&&rs>=re)ctx.addIssue({code:"custom",path:["registrationEndsAt"],message:"پایان ثبت‌نام باید بعد از شروع آن باشد."});if(re&&re>=start)ctx.addIssue({code:"custom",path:["registrationEndsAt"],message:"پایان ثبت‌نام باید پیش از شروع مسابقه باشد."});if(end&&end<=start)ctx.addIssue({code:"custom",path:["endsAt"],message:"پایان مسابقه باید بعد از شروع آن باشد."});});
export type TournamentInput=z.infer<typeof tournamentInputSchema>;
