import { NextResponse } from "next/server";
import { z } from "zod";
import type { RowDataPacket } from "mysql2";
import { authorize } from "@/lib/authorization";
import { writeAuditLog } from "@/lib/audit";
import { db, queryRows } from "@/lib/db";
import { offerNextWaitlistEntries } from "@/lib/waitlist";

const schema=z.object({action:z.enum(["process","cancel"]),tournamentId:z.coerce.number().int().positive().optional(),id:z.coerce.number().int().positive().optional()});
type Row=RowDataPacket&{id:number;status:string;position:number;slots:number;amount:number;created_at:Date;offered_at:Date|null;offer_expires_at:Date|null;tournament_id:number;tournament_title:string;user_name:string;mobile:string|null;team_title:string|null};
export async function GET(){const auth=await authorize('tournaments.manage');if(auth.response)return auth.response;const rows=await queryRows<Row[]>(`SELECT w.id,w.status,w.position,w.slots,w.amount,w.created_at,w.offered_at,w.offer_expires_at,w.tournament_id,t.title AS tournament_title,COALESCE(u.name,'کاربر مهمان قدیمی') AS user_name,u.mobile,w.team_title FROM waitlist_entries w JOIN tournaments t ON t.id=w.tournament_id LEFT JOIN users u ON u.id=w.user_id ORDER BY FIELD(w.status,'OFFERED','WAITING','CONVERTED','EXPIRED','DECLINED','CANCELLED'),t.starts_at,w.position,w.id LIMIT 500`);return NextResponse.json({items:rows.map(r=>({...r,id:String(r.id),tournamentId:String(r.tournament_id),createdAt:new Date(r.created_at).toISOString(),offeredAt:r.offered_at?new Date(r.offered_at).toISOString():null,offerExpiresAt:r.offer_expires_at?new Date(r.offer_expires_at).toISOString():null}))})}
export async function POST(request:Request){const auth=await authorize('tournaments.manage');if(auth.response)return auth.response;try{const input=schema.parse(await request.json());const connection=await db.getConnection();let result:unknown={};try{await connection.beginTransaction();if(input.action==='process'){if(!input.tournamentId){await connection.rollback();return NextResponse.json({message:'مسابقه مشخص نشده است.'},{status:422})}const offered=await offerNextWaitlistEntries(connection,input.tournamentId);result={offered}}else{if(!input.id){await connection.rollback();return NextResponse.json({message:'رکورد مشخص نشده است.'},{status:422})}const[rows]=await connection.query<Array<RowDataPacket&{tournament_id:number;status:string}>>(`SELECT tournament_id,status FROM waitlist_entries WHERE id=? LIMIT 1 FOR UPDATE`,[input.id]);if(!rows[0]){await connection.rollback();return NextResponse.json({message:'رکورد یافت نشد.'},{status:404})}if(!['WAITING','OFFERED'].includes(rows[0].status)){await connection.rollback();return NextResponse.json({message:'این رکورد قابل لغو نیست.'},{status:409})}await connection.execute(`UPDATE waitlist_entries SET status='CANCELLED',cancelled_at=NOW(),updated_at=NOW() WHERE id=?`,[input.id]);await offerNextWaitlistEntries(connection,rows[0].tournament_id);result={cancelled:true}}await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}await writeAuditLog({actorUserId:auth.user.id,action:`waitlist.${input.action}`,entityType:'waitlist',entityId:String(input.id||input.tournamentId||''),newData:result,request});return NextResponse.json({ok:true,...result as object})}catch(error){if(error instanceof z.ZodError)return NextResponse.json({message:'درخواست نامعتبر است.'},{status:422});return NextResponse.json({message:'عملیات صف انتظار انجام نشد.'},{status:500})}}
