/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useEffect,useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { SelectField } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
type Item={id:string;matchId:string;status:string;reason:string;resolution:string|null;createdAt:string;tournament:string;home:string;away:string};type Option={id:string;title:string};
const labels:Record<string,string>={open:"در حال بررسی",accepted:"پذیرفته",rejected:"ردشده",resolved:"رسیدگی‌شده"};
export function DisputesManager(){const[items,setItems]=useState<Item[]>([]);const[matches,setMatches]=useState<Option[]>([]);const[matchId,setMatchId]=useState("");const[reason,setReason]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");async function load(){setLoading(true);const r=await fetch('/api/account/disputes',{cache:'no-store'});const p=await r.json();setLoading(false);if(!r.ok)return setError(p.message||'دریافت اعتراض‌ها انجام نشد.');setItems(p.items||[]);setMatches(p.matches||[]);if(!matchId&&p.matches?.[0])setMatchId(p.matches[0].id)}useEffect(()=>{void load()},[]);async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');const r=await fetch('/api/account/disputes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({matchId:Number(matchId),reason})});const p=await r.json();setSaving(false);if(!r.ok)return setError(p.message||'ثبت اعتراض انجام نشد.');setReason('');await load()}return <><Card className="mt-7 p-6"><h2 className="text-lg font-black">ثبت اعتراض جدید</h2>{matches.length?<form onSubmit={submit} className="mt-5 grid gap-4"><Label>بازی<SelectField value={matchId} onValueChange={setMatchId} options={matches.map(m=>({value:m.id,label:m.title}))}/></Label><Label>شرح اعتراض<Textarea className="min-h-32" value={reason} onChange={e=>setReason(e.target.value)} minLength={10} required/></Label>{error&&<Alert tone="error">{error}</Alert>}<Button type="submit" loading={saving}>ثبت اعتراض</Button></form>:<p className="mt-4 text-sm text-[var(--muted)]">بازی زنده یا پایان‌یافته‌ای برای ثبت اعتراض ندارید.</p>}</Card><div className="mt-5 grid gap-4">{items.map(i=><Card key={i.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{i.tournament} · {i.home} - {i.away}</strong><span className="rounded-full bg-[var(--surface-2)] px-3 py-1 text-xs font-bold">{labels[i.status]||i.status}</span></div><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{i.reason}</p>{i.resolution&&<div className="mt-4 rounded-2xl bg-emerald-500/10 p-4 text-sm leading-7"><strong>پاسخ مدیریت:</strong> {i.resolution}</div>}</Card>)}{!loading&&!items.length&&<Card className="p-8 text-center text-[var(--muted)]">اعتراضی ثبت نشده است.</Card>}</div></>}
