import { NextResponse } from "next/server";
import { z } from "zod";
import type { RowDataPacket } from "mysql2";
import { authorize } from "@/lib/authorization";
import { db } from "@/lib/db";
import { writeAuditLog } from "@/lib/audit";
const schema=z.object({title:z.string().trim().min(3).max(160),gameId:z.number().int().positive(),description:z.string().trim().max(500).optional(),configuration:z.record(z.string(),z.unknown()),isActive:z.boolean()});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await authorize('templates.manage');if(auth.response)return auth.response;try{const input=schema.parse(await request.json());const{id}=await params;const connection=await db.getConnection();let old:RowDataPacket|null=null;try{await connection.beginTransaction();const[rows]=await connection.query<RowDataPacket[]>(`SELECT * FROM tournament_templates WHERE id=? LIMIT 1 FOR UPDATE`,[id]);old=rows[0]||null;if(!old){await connection.rollback();return NextResponse.json({message:'قالب یافت نشد.'},{status:404});}await connection.execute(`UPDATE tournament_templates SET game_id=?,title=?,description=?,configuration=?,is_active=?,updated_at=NOW() WHERE id=?`,[input.gameId,input.title,input.description||null,JSON.stringify(input.configuration),input.isActive?1:0,id]);await connection.commit();}catch(error){await connection.rollback();throw error}finally{connection.release()}await writeAuditLog({actorUserId:auth.user.id,action:'tournament_template.updated',entityType:'tournament_template',entityId:id,oldData:old,newData:input,request});return NextResponse.json({ok:true});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({message:'داده قالب نامعتبر است.',errors:(error as { issues: unknown[] }).issues},{status:422});console.error(error);return NextResponse.json({message:'ویرایش قالب انجام نشد.'},{status:500});}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await authorize('templates.manage');if(auth.response)return auth.response;const{id}=await params;const connection=await db.getConnection();try{await connection.beginTransaction();const[used]=await connection.query<RowDataPacket[]>(`SELECT id FROM tournaments WHERE template_id=? AND deleted_at IS NULL LIMIT 1`,[id]);if(used[0]){await connection.rollback();return NextResponse.json({message:'این قالب در یک مسابقه استفاده شده و فقط می‌توان آن را غیرفعال کرد.'},{status:409});}const[result]=await connection.execute<import('mysql2').ResultSetHeader>(`DELETE FROM tournament_templates WHERE id=?`,[id]);if(!result.affectedRows){await connection.rollback();return NextResponse.json({message:'قالب یافت نشد.'},{status:404});}await connection.commit();await writeAuditLog({actorUserId:auth.user.id,action:'tournament_template.deleted',entityType:'tournament_template',entityId:id,request});return NextResponse.json({ok:true});}catch(error){await connection.rollback();console.error(error);return NextResponse.json({message:'حذف قالب انجام نشد.'},{status:500});}finally{connection.release();}}
